### ISSUE TITLE
[ENHANCE] 预计会新加入的课程

### ISSUE THREAD

**Issue by PKUFlyingPig** [PKUFlyingPig/cs-self-learning#180]
# TODO
## 系统
- [x] 南京大学大操作系统课
- [ ] 南京大计算机系统基础 NEMU
- [ ] 清华大学 rCore
- [ ] Stanford CS140e （C版本/Rust版本）
## 高级数据结构
- [ ] MIT6.851: Advanced Data Structures
- [ ] MIT6.854: Advanced Algorithms
## 程序语言
- [ ] 北京大学编译原理实验
- [ ] LLVM Kaleidoscope in Rust
- [ ] 南京大学软件分析（静态分析）
- [ ] UCB CS164: Compilers and Programming Languages

**Comment by dengyunsheng250** [comment]
所以，答主会添加CS164吗？

**Comment by PKUFlyingPig** [comment]
之前做了一半弃坑了，感觉它 Ocaml 的 lab 偏简单

**Comment by 18024618044** [comment]
1

**Comment by sv158** [comment]
> 之前做了一半弃坑了，感觉它 Ocaml 的 lab 偏简单

@dengyunsheng250 只能说不凑巧，2021年cs164[改版了](https://www.reddit.com/r/berkeley/comments/r4obzf/how_is_the_new_cs_164/)，去掉了2019年以前的chocopy。

旧版存档：

https://web.archive.org/web/20200928065729if_/https://inst.eecs.berkeley.edu/~cs164/sp19/lectures/index.html

备份：https://github.com/taoliq/cs164-sp19

**Comment by yaoyhu** [comment]
南京大学计算机系统基础 NEMU 值得加进去

**Comment by RunxinShao** [comment]
楼主考不考虑加一些agent mcp rag这些内容比如 斯坦福的the modern software engineer

**Comment by UUUserna** [comment]
cs224r会有吗

**Comment by RisingUppercut** [comment]
15440应该难了，cmu应该不会官方公开slide和视频
