### ISSUE TITLE
[ENHANCE] Translate into English version

### ISSUE THREAD

**Issue by PKUFlyingPig** [PKUFlyingPig/cs-self-learning#222]
As many people know, the [original cs-self-learning contents](https://github.com/PKUFlyingPig/Self-learning-Computer-Science) were written in English. Later, for the sake of the domestic audience, I built csdiy in Chinese and maintained it continuously until today, which made the English version outdated. However, recently I received quite a lot of requests to also synchronize the English version. 

Now the website already supports the English version, but the materials haven't been translated yet. If you want to help, the following guide may help you. 

- Pick one file `xxx.md` whose checkbox is empty
- Fork the repo and clone your own copy
- Create `xxx.en.md` under the same directory of `xxx.md` (**xxx must be same**)
- Translate the file and fill it into `xxx.en.md`. You can adjust some sentences to read more fluently and natively. Some online translation tools may help you, like [DeepL](https://www.deepl.com/translator) and [Google Translation](https://translate.google.cn/).
- Create a Pull Request for review. If everything looks good, it will be merged into the main branch and its corresponding checkbox below will be checked. 

# TODO
  - [x] 前言: "index.md"
  - [x] 如何使用这本书: "使用说明.md"
  - [x] 一个仅供参考的CS学习规划: "CS学习规划.md"
  - [x] 必学工具:
      - [x] 翻墙: "必学工具/翻墙.md"
      - [x] Vim: "必学工具/Vim.md"
      - [x] Git: "必学工具/Git.md"
      - [x] GitHub: "必学工具/GitHub.md"
      - [x] "GNU Make": "必学工具/GNU_Make.md"
      - [x] CMake: "必学工具/CMake.md"
      - [x] LaTeX: "必学工具/LaTeX.md"
      - [x] Docker: "必学工具/Docker.md"
      - [x] 实用工具箱: "必学工具/tools.md"
      - [x] 毕业论文: "必学工具/thesis.md"
  - [x] 好书推荐: "好书推荐.md"
  - [x] 数学基础:
      - [x] "MIT18.01/18.02: Calculus": "数学基础/MITmaths.md"
      - [x] #226
      - [x] "MIT6.050J: Information theory and Entropy": "数学基础/information.md"
  - [x] 数学进阶:
      - [x] "UCB CS70: discrete Math and probability theory": "数学进阶/CS70.md"
      - [x] "UCB CS126: probability theory": "数学进阶/CS126.md"
      - [x] "MIT 6.042J: Mathematics for Computer Science": "数学进阶/6.042J.md"
      - [x] "MIT18.330: Introduction to numerical analysis": "数学进阶/numerical.md"
      - [x] "Standford EE364A: Convex Optimization": "数学进阶/convex.md"
      - [x] "The Information Theory, Patter Recognition, and Neural Networks": "数学进阶/The_Information_Theory_Pattern_Recognition_and_Neural_Networks.md"
  - [x] 编程入门:
      - [x] "MIT-Missing-Semester": "编程入门/MIT-Missing-Semester.md"
      - [x] "Harvard CS50: This is CS50x": "编程入门/CS50.md"
      - [x] "UCB CS61A: Structure and Interpretation of Computer Programs": "编程入门/CS61A.md"
      - [x] "Duke University: Introductory C Programming Specialization": "编程入门/Duke-Coursera-Intro-C.md"
      - [x] "Stanford CS106B/X": "编程入门/CS106B_CS106X.md"
      - [x] "Stanford CS106L: Standard C++ Programming": "编程入门/CS106L.md"
      - [x] "Stanford CS110L: Safety in Systems Programming": "编程入门/CS110L.md"
  - [x] 电子基础:
      - [x] "EE16A&B: Designing Information Devices and Systems I&II": "电子基础/EE16.md"
      - [x] "UCB EE120 : Signal and Systems": "电子基础/signal.md"
      - [x] "MIT 6.007 Signals and Systems": "电子基础/Signals_and_Systems_AVO.md"
  - [x] 数据结构与算法:
      - [x] "UCB CS61B: Data Structures and Algorithms": "数据结构与算法/CS61B.md"
      - [x] "Coursera: Algorithms I & II": "数据结构与算法/Algo.md"
      - [x] "UCB CS170: Efficient Algorithms and Intractable Problems": "数据结构与算法/CS170.md"
  - [x] 软件工程:
      - [x] "MIT 6.031: Software Construction": "软件工程/6031.md"
      - [x] "UCB CS169: software engineering": "软件工程/CS169.md"
  - [x] 体系结构:
      - [x] "Coursera: Nand2Tetris": "体系结构/N2T.md"
      - [x] "Digital Design and Computer Architecture": "体系结构/DDCA.md"      
      - [x] "UCB CS61C: Great Ideas in Computer Architecture": "体系结构/CS61C.md"
      - [x] "CMU 15-213: CSAPP": "体系结构/CSAPP.md"
  - [x] 操作系统:
      - [x] "MIT 6.S081: Operating System Engineering": "操作系统/MIT6.S081.md"
      - [x] "UCB CS162: Operating System": "操作系统/CS162.md"
      - [x] "NJU OS: Operating System Design and Implementation": "操作系统/NJUOS.md"
  - [x] 并行与分布式系统:
      - [x] "CMU 15-418/Stanford CS149: Parallel Computing": "并行与分布式系统/CS149.md"
      - [x] "MIT 6.824: Distributed System": "并行与分布式系统/MIT6.824.md"
  - [x] 计算机系统安全:
      - [x] "UCB CS161: Computer Security": "系统安全/CS161.md"
      - [x] "MIT 6.858: Computer System Security": "系统安全/MIT6.858.md"
      - [x] "ASU CSE365: Introduction to Cybersecurity": "系统安全/CSE365.md"
      - [x] "ASU CSE466: Computer Systems Security": "系统安全/CSE466.md"
  - [x] 计算机网络:
      - [x] "USTC Computer Networking:A Top-Down Approach": "计算机网络/topdown_ustc.md"
      - [x] "Computer Networking: A Top-Down Approach": "计算机网络/topdown.md"
      - [x] "Stanford CS144: Computer Network": "计算机网络/CS144.md"
  - [x] 数据库系统:
      - [x] "UCB CS186: Introduction to Database System": "数据库系统/CS186.md"
      - [x] "CMU 15-445: Database Systems": "数据库系统/15445.md"
      - [x] "Caltech CS122: Database System Implementation": "数据库系统/CS122.md"
      - [x] "Stanford CS 346: Database System Implementation": "数据库系统/CS346.md"
      - [x] "CMU 15-799: Special Topics in Database Systems": "数据库系统/15779.md"
  - [x] 编译原理:
      - [x] "Stanford CS143: Compilers": "编译原理/CS143.md"
  - [x] 计算机图形学:
      - [x] "GAMES101": "计算机图形学/GAMES101.md"
      - [x] "GAMES202": "计算机图形学/GAMES202.md"
      - [x] "GAMES103": "计算机图形学/GAMES103.md"
      - [x] "Stanford CS148": "计算机图形学/CS148.md"
  - [x] Web开发:
      - [x] "MIT web development course": "Web开发/mitweb.md"
      - [x] "Stanford CS142: Web Applications": "Web开发/CS142.md"
      - [x] "University of Helsinki: Full Stack open 2022": "Web开发/fullstackopen.md"
  - [x] 数据科学:
      - [x] "UCB Data100: Principles and Techniques of Data Science": "数据科学/Data100.md"
  - [x] 人工智能:
      - [x] "Harvard CS50's Introduction to AI with Python": "人工智能/CS50.md"
      - [x] "UCB CS188: Introduction to Artificial Intelligence": "人工智能/CS188.md"
  - [x] 机器学习:
      - [x] "Coursera: Machine Learning": "机器学习/ML.md"
      - [x] "Stanford CS229: Machine Learning": "机器学习/CS229.md"
      - [x] "UCB CS189: Introduction to Machine Learning": "机器学习/CS189.md"
  - [x] 机器学习系统:
      - [x] "智能计算系统": "人工智能/CYJ.md"
      - [x] "Machine Learning Compilation": "机器学习系统/MLC.md"
      - [x] "CMU 10-414/714: Deep Learning Systems": "机器学习系统/CMU10-414.md"
  - [x] 深度学习:
      - [x] "Coursera: Deep Learning": "深度学习/CS230.md"
      - [x] "国立台湾大学：李宏毅机器学习": "深度学习/LHY.md"
      - [x] "Stanford CS231n: CNN for Visual Recognition": "深度学习/CS231.md"
      - [x] "Stanford CS224n: Natural Language Processing": "深度学习/CS224n.md"
      - [x] "Stanford CS224w: Machine Learning with Graphs": "深度学习/CS224w.md"
      - [x] "UCB CS285: Deep Reinforcement Learning": "深度学习/CS285.md"
  - [x] 机器学习进阶:
      - [x] "进阶路线图": "机器学习进阶/roadmap.md"
      - [x] "CMU 10-708: Probabilistic Graphical Models": "机器学习进阶/CMU10-708.md"
      - [x] "Columbia STAT 8201: Deep Generative Models": "机器学习进阶/STAT8201.md"
      - [x] "U Toronto STA 4273 Winter 2021: Minimizing Expectations": "机器学习进阶/STA4273.md"
      - [x] "Stanford STATS214 / CS229M: Machine Learning Theory": "机器学习进阶/CS229M.md"
  - [ ] 后记: "后记.md"

**Comment by IndifferentArea** [comment]
Maybe I can volunteer to help after I finish this school year.

**Comment by PKUFlyingPig** [comment]
#544
